/**
 * BuildManifest Loader
 * 
 * Loads the build-time manifest artifact for fast editor boot.
 * The BuildManifest is generated by `npm run gen` and served as a static JSON file.
 * 
 * Usage:
 * - Instant sidebar boot (note list with titles/metadata)
 * - Precomputed metadata (title, aliases, tags, status)
 * 
 * NOT reliable for:
 * - File existence (can be stale)
 * - SHA for concurrency (must not be used for saving)
 */

import type { Entry } from "@/lib/content/types";

/**
 * Build-time manifest entry with normalized fields
 */
export interface BuildEntry {
  /** Repo path (e.g., "content/notes/my-note.mdx") */
  path: string;
  /** Slug without content prefix (e.g., "notes/my-note") */
  slug: string;
  /** Note title from frontmatter */
  title: string;
  /** Aliases (not currently used but reserved) */
  aliases?: string[];
  /** Tags from frontmatter */
  tags: string[];
  /** Status from frontmatter (e.g., "to-read", "reading", "done") */
  status?: string;
  /** Date string */
  date?: string;
  /** Updated date string */
  updated?: string;
  /** Content type */
  type: "note" | "article" | "book" | "paper";
  /** Summary from frontmatter */
  summary?: string;
  /** Order key for sorting (derived from build order) */
  order?: number;
}

/**
 * BuildManifest structure
 */
export interface BuildManifest {
  /** List of all entries */
  list: BuildEntry[];
  /** Map by path for O(1) lookup */
  byPath: Map<string, BuildEntry>;
}

/**
 * Converts an Entry from the generated manifest to a BuildEntry
 */
function entryToBuildEntry(entry: Entry, index: number): BuildEntry {
  return {
    path: entry.sourcePath,
    slug: entry.slug,
    title: entry.title,
    tags: entry.tags,
    status: entry.status,
    date: entry.date,
    updated: entry.updated,
    type: entry.type,
    summary: entry.summary,
    order: index,
  };
}

/**
 * Transforms raw manifest array to BuildManifest structure
 */
function transformManifest(entries: Entry[]): BuildManifest {
  const list: BuildEntry[] = [];
  const byPath = new Map<string, BuildEntry>();

  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i];
    const buildEntry = entryToBuildEntry(entry, i);
    list.push(buildEntry);
    byPath.set(buildEntry.path, buildEntry);
  }

  return { list, byPath };
}

/**
 * Cache for the loaded BuildManifest
 */
let cachedManifest: BuildManifest | null = null;
let loadPromise: Promise<BuildManifest> | null = null;

/**
 * Loads the BuildManifest from the static site.
 * 
 * This function:
 * 1. Returns cached manifest if available
 * 2. Deduplicates concurrent requests
 * 3. Gracefully handles missing manifest (returns empty)
 * 4. Does NOT block editor initial render
 * 
 * @returns BuildManifest or empty manifest if unavailable
 */
export async function loadBuildManifest(): Promise<BuildManifest> {
  // Return cached if available
  if (cachedManifest) {
    return cachedManifest;
  }

  // Deduplicate concurrent loads
  if (loadPromise) {
    return loadPromise;
  }

  loadPromise = (async () => {
    try {
      // Fetch from public generated directory
      const response = await fetch("/generated/manifest/manifest.json");
      
      if (!response.ok) {
        console.warn(`BuildManifest: Failed to load (status ${response.status})`);
        return { list: [], byPath: new Map() };
      }

      const entries: Entry[] = await response.json();
      const manifest = transformManifest(entries);
      
      cachedManifest = manifest;
      return manifest;
    } catch (error) {
      console.warn("BuildManifest: Failed to load", error);
      return { list: [], byPath: new Map() };
    } finally {
      loadPromise = null;
    }
  })();

  return loadPromise;
}

/**
 * Clears the cached BuildManifest (useful for testing or force refresh)
 */
export function clearBuildManifestCache(): void {
  cachedManifest = null;
  loadPromise = null;
}

/**
 * Gets the cached BuildManifest synchronously.
 * Returns null if not yet loaded.
 */
export function getCachedBuildManifest(): BuildManifest | null {
  return cachedManifest;
}
